---
title: "Metabolon data summary"
author: "Mafe Senosain"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
library(devtools)
source('/Users/senosam/Documents/Repositories/Research/DH_project01/R/20_Metabolon_vizfunctions.R')
set_environment()
```

# Load data
```{r, echo=FALSE}
load('/Users/senosam/Documents/Massion_lab/Others/Dalton/data/compdata2.RData')
```

# Summary Heatmaps 

## By Metabolites
```{r fig.width = 7, fig.height = 10}
set.seed(194)
suppressMessages(
  dh_heatmap(met_cells, col_names = c('A549_WT', 'A549_KO', 'BEAS2B_WT', 'BEAS2B_OE')))
```

## By Sub-pathway
```{r fig.width = 7, fig.height = 7}
set.seed(194)
suppressMessages(
  dh_heatmap(met_pth, col_names = c('A549_WT', 'A549_KO', 'BEAS2B_WT', 'BEAS2B_OE')))
```

# A549 xCT KO vs A549 WT
## Fold-change plot by metabolites
```{r fig.width = 10, fig.height = 5}
for (i in unique(met_cells$Super_Pathway)){
  n = 30
  if(length(which(met_cells$Super_Pathway == i)) < n ) {
    n = length(which(met_cells$Super_Pathway == i))
  }
  L2FC_barplot(met_cells, 
               max_items = n, 
               superpathway = i, 
               state_col = 'A549_state', 
               L2R_col = 'A549_L2R',
               sum_subpathway = F)
}
```

## Fold-change plot by sub-pathway
```{r fig.width = 10, fig.height = 5}
for (i in unique(met_pth$Super_Pathway)){
  n = 30
  if(length(which(met_pth$Super_Pathway == i)) < n ) {
    n = length(which(met_pth$Super_Pathway == i))
  }
  L2FC_barplot(met_pth, 
               max_items = n, 
               superpathway = i, 
               state_col = 'A549_state', 
               L2R_col = 'A549_L2R',
               sum_subpathway = T)
}
```


# BEAS2B xCT OE vs BEAS2B WT
## Fold-change plot by metabolites
```{r fig.width = 10, fig.height = 5}
for (i in unique(met_cells$Super_Pathway)){
  n = 30
  if(length(which(met_cells$Super_Pathway == i)) < n ) {
    n = length(which(met_cells$Super_Pathway == i))
  }
  L2FC_barplot(met_cells, 
               max_items = n, 
               superpathway = i, 
               state_col = 'BEAS2B_state', 
               L2R_col = 'BEAS2B_L2R',
               sum_subpathway = F)
}
```

## Fold-change plot by sub-pathway
```{r fig.width = 10, fig.height = 5}
for (i in unique(met_pth$Super_Pathway)){
  n = 30
  if(length(which(met_pth$Super_Pathway == i)) < n ) {
    n = length(which(met_pth$Super_Pathway == i))
  }
  L2FC_barplot(met_pth, 
               max_items = n, 
               superpathway = i, 
               state_col = 'BEAS2B_state', 
               L2R_col = 'BEAS2B_L2R',
               sum_subpathway = T)
}
```


